# -*- coding: utf-8 -*-
"""CFD L2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBQ-hgRBy9TKhRChpyh5rCo7yzFAyifR
"""

import matplotlib.pyplot as plt
import numpy as np

# Constantes
k1 = 1.0            #note que esses valores aqui têm que ser menores que o numero inicial de mols para não haver um consumo instantaneo
k2 = 0.65

# Condições iniciais
Ca0 = 0.36  # mol/m3
Cb0 = 0.32  # mol/m3
Cc0 = 0.0  # mol/m3

# Parâmetros para a simulação
n = 500
time = np.zeros(n)
Ca = np.zeros(n)
Cb = np.zeros(n)
Cc = np.zeros(n)

# Condições iniciais
Ca[0] = Ca0
Cb[0] = Cb0
Cc[0] = Cc0
time[-1] = 5

# Constante de equilíbrio
Kc = k2 / k1

# Método de Euler
delta_t = (time[-1] - time[0]) / (n - 1)

for i in range(n - 1):
    # Calcula as taxas de reação com base nas concentrações atuais
    ra = -k1 * (Ca[i] * Cb[i] - Cc[i] / Kc)
    rb = ra
    rc = -ra  # rc é positivo porque C está sendo formado na reação direta

    # Método de Euler para atualizar as concentrações
    Ca[i + 1] = Ca[i] + delta_t * ra
    Cb[i + 1] = Cb[i] + delta_t * rb
    Cc[i + 1] = Cc[i] + delta_t * rc

    # Atualiza o tempo
    time[i + 1] = time[i] + delta_t

fig, axs = plt.subplots()
axs.plot(time, Ca, color ='green', linestyle ='-', label = 'Ca')
axs.plot(time, Cb, color ='blue', linestyle ='-',label = 'Cb')
axs.plot(time, Cc, color ='red', linestyle ='-',label = 'Cc')
plt.grid()
plt.legend()
plt.show()

