# -*- coding: utf-8 -*-
"""Otimzação Aspen/Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyFYHXa-3w8nB-gHim4yXkErHZQwsotN
"""

#Otimizacao aspen

import win32com.client as win32
from mealpy import FloatVar, PSO
import numpy as np
import datetime
import math

aspen=win32.gencache.EnsureDispatch("Apwn.Document")
aspen.InitFromArchive2(r"C:/Users/aluno/Documents/Thiago/simulacoes/simulacoesaspen/SO.bkp")
aspen.Visible = False
aspen.SuppressDialogs = True
aspen.Engine.Run2()

#importando variáveis do aspen para a IDL:

Nt = aspen.Tree.Elements("Data").Elements("Blocks").Elements("T-100").Elements("Output").Elements("ACT_STAGES").Value

aspen.Tree.Elements("Data").Elements("Blocks").Elements("T-100").Elements("Input").Elements("RR").Value = -2.0

aspen.Engine.Run2()

Nt = aspen.Tree.Elements("Data").Elements("Blocks").Elements("T-100").Elements("Output").Elements("ACT_STAGES").Value

aspen.Tree.Elements("Data").Elements("Blocks").Elements("T-100").Elements("Input").Elements("RR").Value = -2.0

col0 = {
    'Name': "Column",
    'RRinput': -1.3, #Input, Fator da RR
    'P': 1.0, #Input, pressão
    'eff': 0.8, #input, eficiencia dos estágios
    'Ureb': 0.6, #0.6 * 3600, #input, coef. transf. calor global, (kJ/h)/(m2K)
    'Ucond': 0.6, #0.6 * 3600, #input, coef. transf. calor global, (kJ/h)/(m2K)
    'RR': 0.0, #output, razao de refluxo
    'Nt': 0.0, #output, estagios teóricos
    'Tcond': 0.0, #output, T do condensador
    'Treb': 0.0, #output, T do refervedor
    'Qcond': 0.0, #output, carga térmica condensador
    'Qreb': 0.0, #output, carga térmica do refervedor
    'Hc': 0.0, #output, altura da coluna
    'Dc': 0.0, #output, diâmetro da coluna
    'Vel': 0.0, #output, velocidade do vapor
    'CCcol': 0.0, #output, custo de capital da coluna
    'Tuf': 0.0, #output, temperatura da utilidade fria
    'Areb': 0.0, #output, área do refervedor
    'CCreb': 0.0, #output, custo de capital do refervedor
    'Tuq': 0.0, #output, temperatura da utilidade quente
    'Acond': 0.0, #output, area do condensador
    'CCcond': 0.0, #output, custo de capital do condensador
    'Dtotal': 0.0, #output, vazão de destilado
    'CC': 0.0, #output, custo de capital da coluna
    'OC': 0.0, #output, custo operacional da coluna
    'TAC': 0.0, #output, CTA da coluna
}

def COL_SET(col):
    block = col['Name']
    aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Input").Elements("RR").Value = col['RRinput']
    Ptopold = aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Input").Elements("PTOP").Value# = col['P']
    if col['P'] < Ptopold:
    #definir primeiro o topo
        aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Input").Elements("PTOP").Value = col['P']
        aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Input").Elements("PBOT").Value = col['P']
    else:
    #definir primeiro o fundo
        aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Input").Elements("PBOT").Value = col['P']
        aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Input").Elements("PTOP").Value = col['P']

def COL_GET(col):
    block = col['Name']
    col['RR'] = aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Output").Elements("ACT_REFLUX").Value
    col['Nt'] = aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Output").Elements("ACT_STAGES").Value
    col['Tcond'] = aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Output").Elements("DISTIL_TEMP").Value
    col['Treb'] = aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Output").Elements("BOTTOM_TEMP").Value
    col['Qcond'] = -aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Output").Elements("COND_DUTY").Value
    col['Qreb'] = aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Output").Elements("REB_DUTY").Value
    DNAME = aspen.Tree.Elements("Data").Elements("Blocks").Elements(block).Elements("Connections").Elements(2).Name
    col['Dtotal'] = aspen.Tree.Elements("Data").Elements("Streams").Elements(DNAME).Elements("Output").Elements("TOT_FLOW").Value

    return col

def utilcost(Temp):
    Cutil =  -0.00000821*Temp**3 + 0.01879380*Temp**2 - 10.18169838*Temp + 1629.93103915
    return Cutil

AF = 0.1
def custo(col):
    col = COL_GET(col)
    #Dimensionamento e custeio da coluna
    #Altura
    col['Hc'] = 0.61 * (col['Nt'] / col['eff']) + 4.27

    #Velocidade do vapor
    col['Vel'] = 0.761 * (1/col['P'])**0.5

    #Diâmetro da coluna
    col['Dc'] = (((4.0 / (math.pi * col['Vel'])) * col['Dtotal'] * (col['RR'] + 1) * 22.4 * (col['Tcond'] / 273.0) * (1 /
    col['P']) * 1.0 / 3600.0)**0.5)

    #Custo de capital da coluna
    col['CCcol'] = (101.9 * col['Dc'] * (col['Hc']**0.802) * 3.18 + 4.7 * col['Dc'] * col['Hc']) * (803/274)

    #Temperaturas das utilidades
    col['Tuq'] = col['Treb'] + 10
    col['Tuf'] = col['Tcond'] - 10

    #Areas do refervedor e condensador
    col['Areb'] = col['Qreb'] / (col['Ureb'] *(col['Tuq'] - col['Treb']))

    #print(col['Tuq'], col['Treb'], col['Areb'])
    col['Acond'] = col['Qcond'] / (col['Ucond'] *(col['Tcond'] - col['Tuf']))

    #Custo de capital do refervedor e condensador
    col['CCreb'] = 101.3 * (col['Areb'] **0.65) * 3.29 * (803/274)
    col['CCcond'] = 101.3 * (col['Acond'] **0.65) * 3.29 * (803/274)

    #Custo de capital total
    col['CC'] = col['CCcol'] + col['CCreb']  + col['CCcond']

    #Custo operacional ($/a)
    col['OC'] = utilcost(col['Tcond']) * col['Qcond'] + utilcost(col['Treb']) * col['Qreb']

    #Custo total anualizado
    col['TAC'] = col['OC'] + AF*col['CC']

    return col

def fobj(X):
    columns = [col0.copy() for _ in range(2)]
    columns[0]['Name'] = "T-100"
    columns[0]['RRinput'] = X[0]
    columns[0]['P'] = X[1]
    columns[1]['Name'] = "T-101"
    columns[1]['RRinput'] = X[2]
    columns[1]['P'] = X[3]
    COL_SET(columns[0])
    COL_SET(columns[1])
    aspen.Engine.Run2()
#Verificando erros na execução
    conv = aspen.Tree.Elements("Data").Elements("Results Summary").Elements("Run-Status").Elements("Output").Elements("PER_ERROR").Value
    if conv == 1:
        Penalty = 10000000.0
    else:
        Penalty = 0.0

    columns[0] = custo(columns[0])
    columns[1] = custo(columns[1])

    TACFinal = columns[0]['TAC'] + columns[1]['TAC'] + Penalty

    return TACFinal

problem_dict = {
    "obj_func": fobj,
    "bounds": FloatVar(lb=[-10.0, 1.0, -10.0, 1.0], ub=[-1.05, 30.0, -1.05, 30.0]),
    "minmax": "min",
}

optimizer = PSO.OriginalPSO(epoch=100, pop_size=40, c1=1.1, c2 = 1.1, w_min=0.3, w_max=0.8)
optimizer.solve(problem_dict)

print(f"Solucao {optimizer.g_best.solution}")
print(f"Funcao objetivo {optimizer.g_best.target.fitness}")

#Obter o tempo atual
now = datetime.datetime.now()

#Formatar data e hora numa string de formato 'dd-mm-aaaa hh-mm'
date_string = now.strftime("%d-%m-%Y %H-%M")

#Construir nome do arquivo e verificar printando na tela
filename = f"SO {date_string}.bkp"

print(filename)
aspen.SaveAs(filename, True)
aspen.Close(r"C:/Users/aluno/Documents/Thiago/simulacoes/simulacoesaspen/SO.bkp")